site_name: xlmtec
site_url: https://Abdur-azure.github.io/xlmtec
repo_url: https://github.com/Abdur-azure/xlmtec
repo_name: xlmtec

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - content.code.copy
  palette:
    scheme: default

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
  - footnotes
  - tables

plugins:
  - search
